# Generated by Django 5.0 on 2023-12-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='DefaultName', max_length=255),
            preserve_default=False,
        ),
    ]
